
  name: test-comments
  on:
    pull_requests

  jobs:
    build:
      runs-on:  ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - runs: cd comments && npm install && npm run test:ci
