
  name: test-others
  on:
    pull_requests

  jobs:
    build:
      runs-on:  ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - runs: cd others && npm install && npm run test:ci
